server:
  port: 8081
  max-http-header-size: 50KB

spring:
  application:
    name: ${entity}-application-microservice
  jackson:
    default-property-inclusion: non_null
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

spring-doc:
  swagger-ui:
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs

management:
  validHeaders: Authorization
  server:
    port: 9201
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: health,prometheus,configprops
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
webclient:
  base-url: http://localhost:8080
  path: /api/v1/{id}